### ISSUE TITLE
WARN 2676 --- [main] com.amazonaws.util.EC2MetadataUtils bug 해결

### ISSUE THREAD

**Issue by JunHo-YH** [dnd-side-project/dnd-6th-7-worry-record-service#5]
aws configure 에서 **key**와 **secret key**  만 입력했을 때 다음과 같은 예외들이 발생하였다.
![캡처](https://user-images.githubusercontent.com/84304802/148789164-1d65d4e3-a6fa-441a-ad52-b15ece7891cf.JPG)

**Comment by PgmJun** [comment]
https://github.com/dnd-side-project/dnd-6th-7-worry-record-service/wiki/Trouble-Shooting#%EF%B8%8F-warn-2676-----main-comamazonawsutilec2metadatautils-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0
